# SKILL TAXONOMY: Maps standard skill names to resume/JD aliases.
SKILL_TAXONOMY = {
    # Programming languages
    "python":            ["python", "python3"],
    "r programming":     ["r programming", "r language"],
    "java":              ["java"],
    "c++":               ["c++", "cpp"],
    "c#":                ["c#", "c sharp"],
    "javascript":        ["javascript", "js", "es6"],
    "typescript":        ["typescript"],
    "sql":               ["sql", "structured query language"],
    "html":              ["html", "html5"],
    "css":               ["css", "css3"],
    "bash":              ["bash", "shell scripting"],

    # Databases
    "microsoft sql server": ["sql server", "mssql", "microsoft sql server", "t-sql", "tsql"],
    "postgresql":        ["postgresql", "postgres"],
    "mysql":             ["mysql"],
    "mongodb":           ["mongodb", "mongo"],
    "nosql":             ["nosql", "no sql"],
    "sqlite":            ["sqlite"],
    "oracle db":         ["oracle db", "oracle database"],
    "snowflake":         ["snowflake"],
    "bigquery":          ["bigquery", "big query"],
    "redshift":          ["redshift"],

    # Data science / ML core
    "machine learning":  ["machine learning", " ml "],
    "deep learning":     ["deep learning", " dl "],
    "data analysis":     ["data analysis", "data analytics"],
    "data cleaning":     ["data cleaning", "data wrangling", "data preprocessing"],
    "eda":               ["eda", "exploratory data analysis"],
    "statistics":        ["statistics", "statistical analysis", "statistical modeling"],
    "feature engineering": ["feature engineering"],
    "regression":        ["regression", "linear regression", "logistic regression"],
    "classification":    ["classification"],
    "clustering":        ["clustering", "k-means", "kmeans"],
    "neural networks":   ["neural network", "neural networks", "cnn", "rnn", "lstm", "gan"],
    "cross validation":  ["cross validation", "cross-validation"],
    "hyperparameter tuning": ["hyperparameter tuning", "grid search", "random search"],
    "model deployment":  ["model deployment", "mlops"],
    "a/b testing":       ["a/b testing", "ab testing"],
    "time series analysis": ["time series analysis", "time series forecasting"],

    # Generative AI & LLM Ecosystem (NEW)
    "natural language processing": ["natural language processing", " nlp "],
    "transformers":      ["transformers", "hugging face", "huggingface"],
    "bert":              ["bert", "distilbert", "mbert", "roberta"],
    "large language models": ["large language models", " llm ", " llms "],
    "vector databases":  ["vector db", "chromadb", "pinecone", "faiss", "qdrant", "milvus"],
    "rag":               ["rag", "retrieval augmented generation"],
    "langchain":         ["langchain"],
    "llama-index":       ["llamaindex", "llama index"],
    "fine-tuning":       ["fine-tuning", "peft", "lora", "qlora"],
    "sentiment analysis": ["sentiment analysis"],
    "named entity recognition": ["named entity recognition", " ner "],
    "text preprocessing": ["text preprocessing", "tokenization", "lemmatization", "stemming"],
    "prompt engineering": ["prompt engineering"],
    "openai api":        ["openai api", "gpt api", "chatgpt api"],
    "gemini api":        ["gemini api"],

    # Python data/ML libraries
    "pandas":            ["pandas"],
    "numpy":             ["numpy"],
    "scikit-learn":      ["scikit-learn", "sklearn", "scikit learn"],
    "tensorflow":        ["tensorflow", "tf keras"],
    "pytorch":           ["pytorch", "torch"],
    "keras":             ["keras"],
    "matplotlib":        ["matplotlib"],
    "seaborn":           ["seaborn"],
    "plotly":            ["plotly"],
    "spacy":             ["spacy"],
    "nltk":              ["nltk"],
    "opencv":            ["opencv", "cv2"],

    # Visualization / BI
    "data visualization": ["data visualization", "dataviz"],
    "tableau":           ["tableau"],
    "power bi":          ["power bi", "powerbi"],
    "excel":             ["excel", "ms excel", "microsoft excel", "vba"],
    "google sheets":     ["google sheets"],

    # Data engineering
    "etl":               ["etl", "extract transform load", "extract, transform, load"],
    "data pipelines":    ["data pipeline", "data pipelines"],
    "apache spark":      ["spark", "apache spark", "pyspark"],
    "hadoop":            ["hadoop"],
    "airflow":           ["airflow", "apache airflow"],
    "data warehousing":  ["data warehouse", "data warehousing"],
    "kafka":             ["kafka", "apache kafka"],

    # Cloud & MLOps
    "aws":               ["aws", "amazon web services"],
    "azure":             ["azure", "microsoft azure"],
    "gcp":               ["gcp", "google cloud platform", "google cloud"],
    "docker":            ["docker"],
    "kubernetes":        ["kubernetes", "k8s"],
    "linux":             ["linux", "unix"],
    "ci/cd":             ["ci/cd", "continuous integration", "continuous deployment"],
    "mlflow":            ["mlflow"],
    "dvc":               ["dvc", "data version control"],
    "weights and biases":["wandb", "weights & biases"],

    # Web & Frontend
    "rest api":          ["rest api", "restful api"],
    "flask":             ["flask"],
    "django":            ["django"],
    "fastapi":           ["fastapi"],
    "streamlit":         ["streamlit"],
    "react":             ["react", "reactjs", "react.js"],
    "next.js":           ["nextjs", "next.js"],
    "tailwind css":      ["tailwind", "tailwind css"],

    # Tools & Practices
    "git":               ["git"],
    "github":            ["github"],
    "gitlab":            ["gitlab"],
    "jira":              ["jira"],
    "confluence":        ["confluence"],
    "version control":   ["version control"],
    "unit testing":      ["unit testing", "pytest", "unittest"],
    "agile":             ["agile", "scrum", "kanban"],
    "microservices":     ["microservices"],
    "powerpoint":        ["powerpoint", "power point", "ms powerpoint"],

    # Soft skills
    "communication skills": ["communication skills", "communication"],
    "problem solving":   ["problem solving", "problem-solving"],
    "teamwork":          ["teamwork", "team player", "collaboration"],
    "leadership":        ["leadership"],
    "critical thinking": ["critical thinking"],
    "time management":   ["time management"],
    "analytical thinking": ["analytical thinking", "analytical skills"],
    "project management": ["project management"],
    "presentation skills": ["presentation skills"],
    "research skills":   ["research skills"],
    "remote work":       ["remote work", "remote team", "distributed team"],
    "adaptability":      ["adaptability", "flexible"],
    "ownership":         ["ownership", "accountability"],
}